services:
  wsp-onpe:
    build: .
    container_name: wsp-onpe-app
    ports:
      - "9000:9000" 
    shm_size: '1gb'
    environment:
      - IS_DOCKER=true
    volumes:
      - ./db.json:/app/db.json
      - ./.wwebjs_auth:/app/.wwebjs_auth
      - ./uploads:/app/uploads
    restart: unless-stopped